### ISSUE TITLE
Htpasswd is not updated when properties change

### ISSUE THREAD

**Issue by erulabs** [rackspace-cookbooks/elkstack#105]
Due to the not_if located here:

https://github.com/rackspace-cookbooks/elkstack/blob/master/recipes/kibana_ssl.rb#L36

The file must be removed for passwords to be updated to match new attributes. There shouldn't be any need for the not_if, as htpasswd takes a fraction of a second and can be safely run every time.

**Comment by martinb3** [comment]
The resource only came with "add" or "overwrite" actions, and add was appending the same 'kibana' user multiple times. We wanted to avoid using the overwrite action because we didn't want to re-write any additional htaccess entries that were added by customers. So our only option was to stop touching the file when it had been created.

**Comment by martinb3** [comment]
I'm honestly not sure which is better. The htpasswd stuff was written with the idea in mind that it was strictly so we didn't leave any wide open services on an initial build, but that we wouldn't provide much customization, expecting customers to use something more secure than htpassword files (the first few we worked with had LDAP or other system users they wanted to use instead).

**Comment by martinb3** [comment]
Please let me know if you have further feedback.

**Comment by erulabs** [comment]
Customers should not be manually updating Chef managed files.

It should be overwritten on over chef run, preferably with a comment in the file mentioning it's being managed by chef.

**Comment by martinb3** [comment]
@erulabs that is a great point. PR submitted to always overwrite the file.
